nama = ["Lisa", "Marwa", "Berlian" ,"Wiwi", "Dipa"]
print ("PENGHUNI BTP")
print("1.",nama[0])
print ("2.",nama[1])
print ("3.",nama[2])
print ("4.",nama[3])
print ("5.",nama[4])
print ("JADWAL CUCI PIRING HARIAN")
print ("SENIN  : ", nama[3])
print ("SELASA : ", nama[4])
print ("RABU   : ", nama[1])
print ("KAMIS  : ", nama[2])
print ("JUM'AT : ", nama[0])
print ("SABTU  : ", nama[2], nama[1], nama[4])
print ("MINGGU : ", nama[0], nama[3])
